[package]
name = "launcher-linux"
version = "0.0.1"
edition = "2021"

[dependencies]
gtk = { version = "0.8", package = "gtk4", features = ["v4_12"] }
tokio = { version = "1", features = ["full"] }

[build-dependencies]
glib-build-tools = "0.19"
