[package]
name = "launcher-util"
version = "0.0.1"
edition = "2021"
license = "GPL-3.0-or-later"
publish = false

[dependencies]
cfg-if = "1"
directories = "5"
once_cell = "1"
thiserror = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
